name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to dockerhub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: docker/setup-buildx-action@v1
    - uses: docker/setup-qemu-action@v1
      
    - name: build+push
      uses: docker/build-push-action@v2
      with:
          cache-from: type=registry,ref=${{ secrets.DOCKER_REPOSITORY }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ secrets.DOCKER_REPOSITORY }}
      
